services:
  app:
    image: dc2021:backend
    ports:
      - 8080:8080
    volumes:
      - ./config.properties:/app/config/application.properties
  client:
    image: dc2021:client
    ports:
      - 80:80
  mongo-db:
    image: mongo:4.4.5-bionic
