services:
  app:
    build: ./
    ports:
      - 8080:8080
    volumes:
      - ./sample-config.properties:/app/config/application.properties
  mongo-db:
    image: mongo:4.4.5-bionic
  mongo-ui:
    image: mongo-express
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-db
