services:
  mongo-db:
    image: mongo:4.4.5-bionic
    ports:
      - 27017:27017
  mongo-ui:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-db
